@echo off
echo Installing npm packages...
call npm install

echo Building Tailwind CSS...
call npm run build

echo Starting Flask server...
start cmd /k "venv\Scripts\activate && flask run"

echo Starting Tailwind watcher...
call npm run watch
